# Información del Add-on
name: "GaztaindiGrill API"
version: "1.0.2"
slug: "gaztaindigrill_api"
description: "API para la parrilla"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false

# Mapeo del puerto de la API
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Puerto de la API de GaztaindiGrill"

# Opciones de configuración
options:
  DB_HOST: "core-mariadb"
  DB_USER: "gaztaindi"
  DB_PASSWORD: "gaztaindi"
  DB_NAME: "gaztaindi"

schema:
  DB_HOST: str
  DB_USER: str
  DB_PASSWORD: password
  DB_NAME: str
